//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enrolltbl
    {
        public int id { get; set; }
        public int courseid { get; set; }
        public int studentid { get; set; }
        public Nullable<decimal> grade { get; set; }
    
        public virtual coursetbl coursetbl { get; set; }
        public virtual studenttbl studenttbl { get; set; }
    }
}
