//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProj.Models
{
    using System;
    
    public enum RatingLevels : byte
    {
        Bad = 1,
        Fair = 2,
        Good = 3,
        Excellent = 4,
        Awesome = 5
    }
}
