//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dropListProj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewCascadingDropDownListsDBEntities : DbContext
    {
        public NewCascadingDropDownListsDBEntities()
            : base("name=NewCascadingDropDownListsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<citiy> citiys { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<state> states { get; set; }
    }
}
