USE [master]
GO
/****** Object:  Database [schooldb]    Script Date: 4/25/2022 8:33:51 PM ******/
CREATE DATABASE [schooldb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'studentdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLCATDB\MSSQL\DATA\studentdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'studentdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLCATDB\MSSQL\DATA\studentdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [schooldb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [schooldb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [schooldb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [schooldb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [schooldb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [schooldb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [schooldb] SET ARITHABORT OFF 
GO
ALTER DATABASE [schooldb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [schooldb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [schooldb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [schooldb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [schooldb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [schooldb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [schooldb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [schooldb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [schooldb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [schooldb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [schooldb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [schooldb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [schooldb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [schooldb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [schooldb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [schooldb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [schooldb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [schooldb] SET RECOVERY FULL 
GO
ALTER DATABASE [schooldb] SET  MULTI_USER 
GO
ALTER DATABASE [schooldb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [schooldb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [schooldb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [schooldb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [schooldb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [schooldb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'schooldb', N'ON'
GO
ALTER DATABASE [schooldb] SET QUERY_STORE = OFF
GO
USE [schooldb]
GO
/****** Object:  Table [dbo].[coursetbl]    Script Date: 4/25/2022 8:33:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[coursetbl](
	[id] [int] NOT NULL,
	[title] [nvarchar](50) NOT NULL,
	[credit] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_coursetbl] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[enrolltbl]    Script Date: 4/25/2022 8:33:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[enrolltbl](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[courseid] [int] NOT NULL,
	[studentid] [int] NOT NULL,
	[grade] [decimal](4, 1) NULL,
 CONSTRAINT [PK_enrolltbl] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[studenttbl]    Script Date: 4/25/2022 8:33:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[studenttbl](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fname] [nvarchar](50) NOT NULL,
	[lname] [nvarchar](50) NOT NULL,
	[enrolldate] [date] NULL,
	[imgPath] [nvarchar](250) NULL,
 CONSTRAINT [PK_studenttbl] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_enrolltbl]    Script Date: 4/25/2022 8:33:51 PM ******/
CREATE NONCLUSTERED INDEX [IX_enrolltbl] ON [dbo].[enrolltbl]
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[enrolltbl]  WITH CHECK ADD  CONSTRAINT [FK_enrolltbl_coursetbl] FOREIGN KEY([courseid])
REFERENCES [dbo].[coursetbl] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[enrolltbl] CHECK CONSTRAINT [FK_enrolltbl_coursetbl]
GO
ALTER TABLE [dbo].[enrolltbl]  WITH CHECK ADD  CONSTRAINT [FK_enrolltbl_studenttbl] FOREIGN KEY([studentid])
REFERENCES [dbo].[studenttbl] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[enrolltbl] CHECK CONSTRAINT [FK_enrolltbl_studenttbl]
GO
USE [master]
GO
ALTER DATABASE [schooldb] SET  READ_WRITE 
GO
